-- Explainer - this is the raw inventory data, not yet enriched

WITH raw_inventory AS (
   -- This looks at your sources.yml file to find the raw BigQuery table
   SELECT * FROM {{ source('raw_shopify', 'raw_inventory_table') }}
)


SELECT
   -- Wrapping the messy names in backticks and renaming them using AS
   `Handle` AS handle,
   `Title` AS title,
   `Option1 Name` AS option1_name,
   `Option1 Value` AS option1_value,
   `Option2 Name` AS option2_name,
   `Option2 Value` AS option2_value,
   `Option3 Name` AS option3_name,
   `Option3 Value` AS option3_value,
   `SKU` AS sku,
   `HS Code` AS hs_code,
   `COO` AS coo,
   `Location` AS `location`,
   `Bin name` AS bin_name,
    SAFE_CAST(`Incoming _not editable_` AS INT64) AS incoming,
    SAFE_CAST(`Unavailable _not editable_` AS INT64) AS unavailable,
    SAFE_CAST(`Committed _not editable_` AS INT64) AS `committed`,
    SAFE_CAST(`Available _not editable_` AS INT64) AS available,
    SAFE_CAST(`On hand _current_` AS INT64) AS on_hand_current,
    SAFE_CAST(`On hand _new_` AS INT64) AS on_hand_new
FROM raw_inventory
